---
- name: apt update
  apt:
    update_cache: yes

- name: apt upgrade
  apt:
    upgrade: dist

- name: Install Docker.io package
  become: yes
  apt:
    name: docker.io
    state: present

- name: Start and enable Docker service
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Check Docker version
  become: yes
  command: docker --version
  register: docker_version

- name: Display Docker version
  debug:
    msg: "Installed Docker version: {{ docker_version.stdout }}"