---
- name: apt update
  apt:
    update_cache: yes

- name: apt upgrade
  apt:
    upgrade: dist

- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present
    update_cache: yes

- name: Ensure snapd service is enabled and started
  systemd:
    name: snapd
    enabled: yes
    state: started

- name: Install Docker using snap
  snap:
    name: docker
    state: present

- name: Check Docker version
  become: yes
  command: docker --version
  register: docker_version

- name: Display Docker version
  debug:
    msg: "Installed Docker version: {{ docker_version.stdout }}"