---
- name: apt update
  apt:
    update_cache: yes

- name: apt upgrade
  apt:
    upgrade: dist

- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present
    update_cache: yes

- name: Ensure snapd service is enabled and started
  systemd:
    name: snapd
    enabled: yes
    state: started

- name: Install Docker using snap
  snap:
    name: docker
    state: present

- name: Check Docker version
  command: docker --version
  register: docker_version

- name: Display Docker version
  debug:
    msg: "Installed Docker version: {{ docker_version.stdout }}"

- name: Install Java
  apt:
    name: openjdk-17-jdk
    state: present

- name: Add Jenkins GPG key
  shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

- name: Add Jenkins repository
  shell: echo 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/' | tee /etc/apt/sources.list.d/jenkins.list > /dev/null

- name: apt update
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start and enable Jenkins service
  shell: systemctl start jenkins && systemctl enable jenkins

- name: Get Jenkins initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_admin_password

- name: Display Jenkins initial admin password
  debug:
    msg: "Jenkins initial admin password: {{ jenkins_admin_password.stdout }}"