---
- import_tasks: ../common/tasks.yml

- name: Install node and npm
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Create or update active_color.txt file
  shell: echo "blue" > /var/lib/jenkins/active_color.txt
  args:
    creates: /var/lib/jenkins/active_color.txt
