# vars.yml
packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_gpg_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_gpg_key_file: /etc/apt/keyrings/docker.gpg
architecture: "{{ ansible_architecture }}"
distribution_release: "{{ ansible_distribution_release }}"
docker_list_file: /etc/apt/sources.list.d/docker.list
docker_repo_url: "https://download.docker.com/linux/ubuntu"
